- app/policies/user_role_policy.rb
- spec/controllers/user_roles_controller_spec.rb
issue#164
UserRoles endpoint will return an empty list instead of Unauthorized
> UserRoles endpoint will return an empty list instead of unauthorized

- Gemfile
- Gemfile.lock
- app/controllers/categories_controller.rb
- app/controllers/indicators_controller.rb
- app/controllers/measures_controller.rb
- app/controllers/progress_reports_controller.rb
- app/controllers/recommendations_controller.rb
- app/models/application_record.rb
- app/policies/category_policy.rb
- app/policies/indicator_policy.rb
- app/policies/measure_policy.rb
- app/policies/recommendation_policy.rb
- app/policies/user_policy.rb
- app/serializers/application_serializer.rb
- spec/controllers/categories_controller_spec.rb
- spec/controllers/indicators_controller_spec.rb
- spec/controllers/measures_controller_spec.rb
- spec/controllers/progress_reports_controller_spec.rb
- spec/controllers/recommendations_controller_spec.rb
- spec/controllers/users_controller_spec.rb
Issue #155 
- Reverted attempt to build as ActiveRecord module
- Implemented rejection in controllers
- Reject updates where updated_at field sent is older than the field on the server
> Reject updates where updated_at is older than the the server issue#155

- app/controllers/users_controller.rb
- app/models/user.rb
- spec/controllers/users_controller_spec.rb
Issue #155 
- Added in support for updated_at check for Users
- When a user is deleted, so are it's user_roles
> Added in support for updated_at check for Users.  issue#155

- spec/controllers/progress_reports_controller_spec.rb
This was changed in bb687a69339aaa3501f24140907e9a2135ffe4c5 for #154
so it makes sense to update the spec to allow for this because it will
otherwise just keep failing.
> Allow contributors to create progress reports for indicators.

- app/controllers/categories_controller.rb
- app/controllers/due_dates_controller.rb
- app/controllers/indicators_controller.rb
- app/controllers/measure_categories_controller.rb
- app/controllers/measure_indicators_controller.rb
- app/controllers/measures_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/progress_reports_controller.rb
- app/controllers/recommendations_controller.rb
- app/controllers/sdgtargets_controller.rb
- app/controllers/taxonomies_controller.rb
- spec/controllers/categories_controller_spec.rb
- spec/controllers/due_dates_controller_spec.rb
- spec/controllers/indicators_controller_spec.rb
- spec/controllers/measures_controller_spec.rb
- spec/controllers/pages_controller_spec.rb
- spec/controllers/progress_reports_controller_spec.rb
- spec/controllers/recommendation_measures_controller_spec.rb
- spec/controllers/recommendations_controller_spec.rb
- spec/controllers/roles_controller.rb
- spec/controllers/sdgtargets_controller_spec.rb
- spec/controllers/taxonomies_controller_spec.rb
- spec/controllers/users_controller_spec.rb
We have an issue since the performance improvements to #299 where the
latest last_modified_user_id wasn't being returned from PUT /update
This was due to the instance of the record not being reloaded after it
was updated given that last_modified_user_id is now a cached lookup
from the versions table.
By specifically reloading this in the controller we get the latest.
> Ensure latest last_modified_user_id from PUT update

- app/controllers/categories_controller.rb
- app/controllers/due_dates_controller.rb
- app/controllers/indicators_controller.rb
- app/controllers/measures_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/progress_reports_controller.rb
- app/controllers/recommendations_controller.rb
- app/controllers/sdgtargets_controller.rb
- app/controllers/taxonomies_controller.rb
- app/models/application_record.rb
- app/models/user.rb
- app/models/versioned_record.rb
- app/serializers/category_serializer.rb
- app/serializers/due_date_serializer.rb
- app/serializers/fast_application_serializer.rb
- app/serializers/fast_versioned_serializer.rb
- app/serializers/indicator_serializer.rb
- app/serializers/measure_serializer.rb
- app/serializers/page_serializer.rb
- app/serializers/progress_report_serializer.rb
- app/serializers/recommendation_serializer.rb
- app/serializers/sdgtarget_serializer.rb
- app/serializers/user_serializer.rb
- db/migrate/20180528083426_add_last_modified_user_id_to_versioned_records.rb
- db/schema.rb
- spec/controllers/users_controller_spec.rb
In order to reduce reading overhead we are now caching the
`last_modified_user_id` on save for each versioned record.  This allows
the queries to be simpler, and therefore faster, in most cases.
This increases overhead when writing but given the benefits of API
performance when reading it seems worth it.
> Simplify last_modified_user_id by caching it

- app/models/versioned_record.rb
- spec/controllers/categories_controller_spec.rb
Previously we could hit a situation on a DELETE action where we would
try to `cache_last_modified_user_id` which is invalid because it's being
deleted.
Added a spec to categories which is where this issues was located.
> Avoid cache_last_modified_user_id on DELETE

- spec/factories/bookmarks.rb
9 bookmark_controller_specs were failing due to the factory still having bookmark_type in it although that was removed from the model
> bookmark type doesn't exist anymore

- app/policies/indicator_policy.rb
- app/policies/measure_policy.rb
- app/serializers/measure_serializer.rb
- db/migrate/20231212214117_add_reference_to_measures.rb
- db/schema.rb
We want to add a reference field to the measures table, which should be
optional.
When running `bin/rails db:migrate`, Rails re-formatted `db/schema.rb`.
Resolves #361
> Add optional `reference` field to measures

- app/mailers/due_date_mailer.rb
- app/views/due_date_mailer/category_overdue.en.text.erb
- config/application.rb
- config/locales/en-NZ.yml
- spec/mailers/due_date_mailer_spec.rb
Fixes #368 by localising due dates into the NZ `date_format`.
While implementing this, I noticed that the due date mailer had a few
issues in the implementation and the specs, so I've fixed these.
> Localise date format in due date mailer

- config/environments/production.rb
Closes #369
We want to remove mention of the word "Mailgun" as these aren't specific
to any particular service.
I also noticed that the `EMAIL_ENABLED` case was misleading as it was
disabling email when set to true.
> Rename SMTP environment variables to remove "Mailgun"

- app/models/category.rb
- app/models/recommendation.rb
quick fix to address: #385 
eventually the recommendation model should merge direct and indirect indicators, so that there is no need to change the category model
> Add recommendation indicators via measures

- app/jobs/application_job.rb
- spec/mailers/due_date_mailer_spec.rb
We noticed that the `DueDateMailer` was sending emails with dates that
were not localised into `en-NZ`.  
As it turns out, the job runner's locale was not the same as the
application's locale so setting this in the `ApplicationJob` file fixes
the issue.
Fixes #368
> Set `I18n.locale` in the job running environment.

- app/jobs/application_job.rb
- app/mailers/due_date_mailer.rb
When sending emails using the clockwork scheduler the `I18n.locale` is 
still not being picked up properly, so we can switch to using the block
level `I18n.with_locale` which lets us supply the locale to use for the
current block of code.
> Switch from setting `I18n.locale` to using `I18n.with_locale`

- app/controllers/users_controller.rb
- app/policies/user_policy.rb
- spec/controllers/users_controller_spec.rb
- spec/models/indicator_spec.rb
Following on from #364 we want to ensure that when retrieving a group of
users that we apply the right email and domain visibility policy.
Resolves #364.
> Ensure that emails and domains are visible at appropriate times

- app/models/indicator.rb
- app/models/measure.rb
- app/models/recommendation.rb
- db/migrate/20240505021300_enforce_reference_uniqueness_on_indicators_measures_recommendations.rb
- db/schema.rb
- spec/factories/indicators.rb
- spec/factories/measures.rb
- spec/factories/recommendations.rb
- spec/models/indicator_spec.rb
- spec/models/measure_spec.rb
- spec/models/recommendation_spec.rb
We want to make sure that the `reference` is unique for `indicators`,
`measures`, and `recommendations` so this adds a validation to each of
the models and also a unique index to the database table.
Closes #395
> Enforce `reference` uniqueness for `indicators`, `measures`, `recommendations`

- app/jobs/send_progress_report_updated_emails_job.rb
- app/mailers/progress_report_mailer.rb
- app/models/category.rb
- app/models/progress_report.rb
- app/views/due_date_mailer/category_overdue.en.text.erb
- app/views/progress_report_mailer/updated.en.html.erb
- app/views/progress_report_mailer/updated.en.text.erb
- config/locales/en.yml
- scheduler.rb
- spec/mailers/progress_report_mailer_spec.rb
- spec/models/progress_report_spec.rb
Resolves #397 by sending an email to each category manager when a
progress report in their category is updated.
> Notify category manager when progress report updated

- app/models/recommendation.rb
- app/policies/recommendation_policy.rb
- app/serializers/recommendation_serializer.rb
- db/migrate/20240726032048_add_support_level_to_recommendations.rb
- db/schema.rb
- spec/controllers/recommendations_controller_spec.rb
- spec/models/recommendation_spec.rb
https://github.com/impactoss/impactoss-server/issues/404
> Add integer field "support_level" to recommendations table and make
> available for the usual create, read and update operations.
>
> Background: this will eventually replace the boolean "accepted" field
> as the UN system is introducing a third response option. "Accepted"
> and "Noted" will be replaced with "Supported", "Supported in part" and
> "Noted" (which we will encode as 2, 1, and 0 - in addition we will
> have -1 or "null" for "not applicable")
This commit adds a `support_level` field to the Recommendations table
with an enum-based value:
```ruby
{
"noted" => 0,
"supported_in_part" => 1,
"supported" => 2
}
```
At this stage, the field is optional so we can use a null value to
to represent "not applicable". Once we have …
> Add support_level integer to recommendations

- app/models/indicator.rb
- app/models/measure.rb
- db/migrate/20240910012254_make_reference_and_title_fields_mandatory.rb
- db/schema.rb
- spec/controllers/indicators_controller_spec.rb
- spec/controllers/measures_controller_spec.rb
- spec/models/indicator_spec.rb
- spec/models/measure_spec.rb
https://github.com/impactoss/impactoss-server/issues/403
This commit makes the following fields mandatory (table: field):
```
measures: reference
indicators: reference
pages: title
categories: title
progress_reports: title
```
It also updates the model validations and specs accordingly.
The data migration sets any currently null values to `""` rather than
applying a more nuanced strategy. I'd like to confirm that this is okay
before we go ahead.
> Make various reference and title fields mandatory

- app/controllers/application_controller.rb
Fixes [https://github.com/impactoss/impactoss-server/security/code-scanning/1](https://github.com/impactoss/impactoss-server/security/code-scanning/1)
To fix the problem, we need to ensure that CSRF protection is not weakened for JSON requests. Instead of using `protect_from_forgery with: :null_session`, we should use `protect_from_forgery with: :exception` for all request formats. This will raise an exception if an invalid CSRF token is provided, ensuring that all requests are properly validated.
We will modify the `protect_from_forgery` line to remove the conditional weakening for JSON requests. This change will be made in the `app/controllers/application_controller.rb` file.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Fix code scanning alert no. 1: CSRF protection weakened or disabled
